version: '3.5'

services:
  apache:
    image: 'apache-php:wiconsult'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app:/app
      
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    ports:
       - 80:8080
    volumes:
      - app:/srv

volumes:
  app: 
